from __future__ import annotations

import csv
import shutil
from pathlib import Path


def _latex_escape(value: str) -> str:
    # Minimal LaTeX escaping for common special chars.
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "_": r"\_",
        "#": r"\#",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = str(value)
    for k, v in replacements.items():
        out = out.replace(k, v)
    return out


def _is_number(s: str) -> bool:
    try:
        float(s)
        return True
    except Exception:
        return False


def write_csv_as_latex_table(
    csv_path: Path,
    tex_path: Path,
    caption: str,
    label: str,
) -> None:
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError(f"Empty CSV header: {csv_path}")

        headers = list(reader.fieldnames)
        rows = list(reader)

    # Infer alignment: first column left, others right if numeric else left
    align = []
    for idx, h in enumerate(headers):
        if idx == 0:
            align.append("l")
            continue
        col_vals = [r.get(h, "") for r in rows]
        align.append("r" if all(_is_number(v) for v in col_vals if str(v).strip() != "") else "l")

    lines: list[str] = []
    lines.append("% -*- coding: utf-8 -*-")
    lines.append("% Auto-generated by run_export_saliency_at_to_thesis.py")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"  \centering")
    # caption/label are treated as LaTeX-safe strings (may contain commands like \%).
    lines.append(f"  \\caption{{{caption}}}")
    lines.append(f"  \\label{{{label}}}")
    lines.append(f"  \\begin{{tabular}}{{{''.join(align)}}}")
    lines.append(r"    \toprule")

    header_line = "      " + " & ".join([r"\textbf{" + _latex_escape(h) + "}" for h in headers]) + r" \\" 
    lines.append(header_line)
    lines.append(r"    \midrule")

    for r in rows:
        vals = []
        for h in headers:
            v = r.get(h, "")
            v = "" if v is None else str(v)
            # Keep numeric formatting compact
            if _is_number(v):
                fv = float(v)
                v = f"{fv:.2f}" if abs(fv) >= 1 else f"{fv:.4f}".rstrip("0").rstrip(".")
            vals.append(_latex_escape(v))
        lines.append("    " + " & ".join(vals) + r" \\")

    lines.append(r"    \bottomrule")
    lines.append(r"  \end{tabular}")
    lines.append(r"\end{table}")
    tex_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    repo_root = Path(__file__).resolve().parent
    src_results = repo_root / "results_figures"

    thesis_root = Path(r"D:\\软件\\南开大学论文模板2026")
    export_fig = thesis_root / "figures" / "exp_saliency_at"
    export_tab = thesis_root / "tables" / "exp_saliency_at"

    export_fig.mkdir(parents=True, exist_ok=True)
    export_tab.mkdir(parents=True, exist_ok=True)

    png_files = [
        "training_curve_AdaptiveSaliencyAT_5_1.png",
        "eval_adaptive_n_param_5_1.png",
        "eval_adaptive_r_param_5_1.png",
        "eval_color_param_5_1.png",
        "whitebox_vs_transfer_comparison.png",
        "adaptive_saliency_at_comparison_5_1.png",
        "adaptive_saliency_at_robustness_bar_5_1.png",
        "adaptive_saliency_at_param_sensitivity_5_1.png",
    ]

    csv_files = [
        "adaptive_saliency_at_training_history_5_1.csv",
        "adaptive_saliency_at_evaluation_results.csv",
        "adaptive_saliency_at_comparison.csv",
        "whitebox_vs_transfer_attack_comparison.csv",
    ]

    copied: list[str] = []
    missing: list[str] = []

    def copy_if_exists(name: str, dst_dir: Path) -> None:
        src = src_results / name
        if not src.exists():
            missing.append(str(src))
            return
        dst = dst_dir / name
        shutil.copy2(src, dst)
        copied.append(str(dst))

    for f in png_files:
        copy_if_exists(f, export_fig)
    for f in csv_files:
        copy_if_exists(f, export_tab)

    # Generate LaTeX table for experiment.tex: \ref{tab:transfer}
    transfer_csv = export_tab / "whitebox_vs_transfer_attack_comparison.csv"
    transfer_tex = export_tab / "tab_transfer.tex"
    if transfer_csv.exists():
        write_csv_as_latex_table(
            csv_path=transfer_csv,
            tex_path=transfer_tex,
            caption="Adaptive-Saliency-AT(N=5,R=3)在白盒与迁移攻击下的准确率对比（\\%）",
            label="tab:transfer",
        )
    else:
        missing.append(str(transfer_csv))

    print("[EXPORT] Source:", src_results)
    print("[EXPORT] Figures ->", export_fig)
    print("[EXPORT] Tables  ->", export_tab)
    print()
    print("[OK] Copied:", len(copied))
    if copied:
        for p in copied:
            print("  -", p)
    if missing:
        print("\n[WARN] Missing:")
        for p in missing:
            print("  -", p)

    if transfer_tex.exists():
        print("\n[OK] Generated:")
        print("  -", transfer_tex)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
